- src: geerlingguy.adminer
  version: 1.1.0

- src: geerlingguy.composer
  version: 1.4.1

- src: geerlingguy.git
  version: 1.1.1

- src: debops.mariadb
  version: v0.2.2

- src: debops.mariadb_server
  version: v0.2.4

- src: geerlingguy.nginx
  version: 1.8.0

- src: geerlingguy.php
  version: 3.2.2

- src: geerlingguy.php-xdebug
  version: 2.1.1

- src: igor_mukhin.cron
  version: v0.3.0
