---

dependencies: []

galaxy_info:
  author: igor_mukhin
  description: Installs and configures cron
  galaxy_tags:
    - web
  min_ansible_version: 1.6
  license: MIT
  platforms:
    - name: Ubuntu
      versions:
        - all
    - name: Debian
      versions:
        - all
  categories:
    - system
